server:
  port: 8080

# 교육용 코드
superuser:
  userId: ${_SUPER_UID:admin123}
---

spring:
  profiles: default
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#  datasource:
#    url: jdbc:mysql://${_DATASOURCE_ADDRESS:35.221.110.118:3306}/${_DATASOURCE_TABLESPACE:my-database}
#    username: ${_DATASOURCE_USERNAME:root}
#    password: ${_DATASOURCE_PASSWORD:secretpassword}
#    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8088

#api:
#  url:
#    delivery: http://localhost:8082
---
spring:
  profiles: docker
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL57Dialect
#  datasource:
#    url: jdbc:mysql://${_DATASOURCE_ADDRESS:35.221.110.118:3306}/${_DATASOURCE_TABLESPACE:my-database}
#    username: ${_DATASOURCE_USERNAME:root}
#    password: ${_DATASOURCE_PASSWORD:secretpassword}
#    driverClassName: com.mysql.cj.jdbc.Driver
