apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: gcr.io/event-storming/monolith:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-storage
              mountPath: /data/log_data
      volumes:
        - name: log-storage
          emptyDir: {}