apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: gcr.io/event-storming/monolith:latest
          ports:
            - containerPort: 8080
          env:
            - name: _DATASOURCE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: datasource.address
            - name: _DATASOURCE_TABLESPACE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: datasource.tablespace
            - name: _DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: datasource.username
            - name: _DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: datasource.password