apiVersion: v1
kind: PersistentVolume
metadata:
  name: readonly-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: disk-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 3Gi
  volumeName: readonly-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: gcr.io/event-storming/monolith:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: log-storage
              mountPath: /data/log_data
      volumes:
        - name: log-storage
          persistentVolumeClaim:
            claimName: test-pv-claim
            readOnly: true